from PyQt5 import QtWidgets
from PyQt5.QtCore import Qt

from Desktop.ui import ui_styles as S
from Desktop.ui import ui_texts as T


class AccountDialogUiMixin:
    def setup_account_ui(self, api_base_url):
        self.setWindowFlags(self.windowFlags() & ~Qt.WindowContextHelpButtonHint)
        self.setWindowTitle(T.ACCOUNT_CENTER_TITLE)
        self.setMinimumSize(760, 560)

        root = QtWidgets.QVBoxLayout(self)
        root.setContentsMargins(18, 18, 18, 18)
        root.setSpacing(12)

        form = QtWidgets.QFormLayout()
        form.setLabelAlignment(Qt.AlignRight | Qt.AlignVCenter)
        form.setFormAlignment(Qt.AlignLeft | Qt.AlignTop)
        form.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        form.setHorizontalSpacing(12)
        form.setVerticalSpacing(12)

        def make_row_label(text):
            label = QtWidgets.QLabel(text)
            label.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
            label.setMinimumHeight(36)
            label.setStyleSheet(S.ROW_LABEL_STYLE)
            return label

        self.edit_api_base = QtWidgets.QLineEdit(api_base_url)
        self.edit_api_base.setPlaceholderText(T.PLACEHOLDER_API)
        self.edit_api_base.setReadOnly(True)
        self.edit_api_base.setFocusPolicy(Qt.NoFocus)
        self.edit_api_base.setStyleSheet(S.READONLY_STYLE)
        self.edit_api_base.setMinimumHeight(34)
        self.btn_copy_api = QtWidgets.QPushButton(T.BUTTON_COPY)
        self.btn_copy_api.setStyleSheet(S.SECONDARY_BUTTON_STYLE)
        self.btn_copy_api.setFixedWidth(92)
        self.btn_copy_api.setFixedHeight(34)
        api_row = QtWidgets.QWidget()
        api_row.setMinimumHeight(36)
        api_layout = QtWidgets.QHBoxLayout(api_row)
        api_layout.setContentsMargins(0, 0, 0, 0)
        api_layout.setSpacing(8)
        api_layout.setAlignment(Qt.AlignVCenter)
        api_layout.addWidget(self.edit_api_base, 1)
        api_layout.addWidget(self.btn_copy_api)
        form.addRow(make_row_label(T.LABEL_API), api_row)

        self.view_username = QtWidgets.QLineEdit()
        self.view_username.setReadOnly(True)
        self.view_username.setFocusPolicy(Qt.NoFocus)
        self.view_username.setStyleSheet(S.READONLY_STYLE)
        self.view_username.setMinimumHeight(34)
        self.btn_copy_username = QtWidgets.QPushButton(T.BUTTON_COPY)
        self.btn_copy_username.setStyleSheet(S.SECONDARY_BUTTON_STYLE)
        self.btn_copy_username.setFixedWidth(92)
        self.btn_copy_username.setFixedHeight(34)
        username_row = QtWidgets.QWidget()
        username_row.setMinimumHeight(36)
        username_layout = QtWidgets.QHBoxLayout(username_row)
        username_layout.setContentsMargins(0, 0, 0, 0)
        username_layout.setSpacing(8)
        username_layout.setAlignment(Qt.AlignVCenter)
        username_layout.addWidget(self.view_username, 1)
        username_layout.addWidget(self.btn_copy_username)
        form.addRow(make_row_label(T.LABEL_CURRENT_ACCOUNT), username_row)

        self.view_password = QtWidgets.QLineEdit()
        self.view_password.setReadOnly(True)
        self.view_password.setFocusPolicy(Qt.NoFocus)
        self.view_password.setStyleSheet(S.READONLY_STYLE)
        self.view_password.setMinimumHeight(34)
        self.btn_copy_password = QtWidgets.QPushButton(T.BUTTON_COPY)
        self.btn_copy_password.setStyleSheet(S.SECONDARY_BUTTON_STYLE)
        self.btn_copy_password.setFixedWidth(92)
        self.btn_copy_password.setFixedHeight(34)
        password_row = QtWidgets.QWidget()
        password_row.setMinimumHeight(36)
        password_layout = QtWidgets.QHBoxLayout(password_row)
        password_layout.setContentsMargins(0, 0, 0, 0)
        password_layout.setSpacing(8)
        password_layout.setAlignment(Qt.AlignVCenter)
        password_layout.addWidget(self.view_password, 1)
        password_layout.addWidget(self.btn_copy_password)
        form.addRow(make_row_label(T.LABEL_CURRENT_PASSWORD), password_row)
        root.addLayout(form)

        row = QtWidgets.QHBoxLayout()
        row.setSpacing(8)
        self.btn_refresh_jobs = QtWidgets.QPushButton(T.BUTTON_REFRESH_JOBS)
        self.btn_refresh_jobs.setStyleSheet(S.PRIMARY_BUTTON_STYLE)
        self.btn_refresh_jobs.setMinimumHeight(36)
        row.addWidget(self.btn_refresh_jobs)
        root.addLayout(row)

        self.label_status = QtWidgets.QLabel("")
        self.label_status.setMinimumHeight(30)
        self.label_status.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        self.label_status.setContentsMargins(10, 0, 10, 0)
        root.addWidget(self.label_status)

        self.jobs_table = QtWidgets.QTableWidget(0, 4)
        self.jobs_table.setHorizontalHeaderLabels(T.TABLE_HEADERS)
        self.jobs_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.jobs_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.jobs_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.jobs_table.setWordWrap(False)
        self.jobs_table.setAlternatingRowColors(True)
        self.jobs_table.verticalHeader().setVisible(False)
        self.jobs_table.verticalHeader().setDefaultSectionSize(30)
        header = self.jobs_table.horizontalHeader()
        header.setHighlightSections(False)
        header.setStretchLastSection(False)
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)
        self.jobs_table.setStyleSheet(S.JOBS_TABLE_STYLE)
        root.addWidget(self.jobs_table, 1)

